### ISSUE TITLE
Extend IDN-TH to include RIF-CS vocabs terms

### ISSUE THREAD

**Issue by jamiefeiss** [idn-au/vocab-data#24]
For the ARDC’s [vocabularies of classification terms recommended for use with RIF-CS](https://archive-intranet.ardc.edu.au/display/DOC/Subject), determine which, if any, terms within those vocabularies indicate indigineity and include them within IDN-TH.

**Comment by leskneebone** [comment]
On Tuesday 17 September Richard Ferrers (ARDC) wrote:

Hi Les, cc Services

Nice to hear from you. Please find some (1) RIF-CS documentation and links and (2) Answer at the very bottom.

1.Links.
You can see the publication of RIF-CS at: https://vocabs.ardc.edu.au/viewById/1

You can see the Registry system on Github (where you can add a pull request): https://github.com/au-research/ANDS-Registry-Core

You can see documentation at:  https://documentation.ardc.edu.au/cpg/create-metadata-content-for-research-data-australi

You can see RIF-CS updates at: https://documentation.ardc.edu.au/updates/rif-cs-schema-updates
Assistance with crosswalks is [available](mailto:services@ardc.edu.au). (Email: [services@ardc.edu.au](mailto:services@ardc.edu.au))
Request support: [services@ardc.edu.au](mailto:services@ardc.edu.au)
​
Schema definitions is at: https://researchdata.edu.au/documentation/rifcs/schemadocs/registryObjects.html

2. RIF-CS changes
In the past a RIF-CS changes, were approved (annually) through a RIF-CS Advisory Board (now inactive group). If you would like a new term added to a vocabulary, email [services@ardc.edu.au](mailto:services@ardc.edu.au). 
Source: https://documentation.ardc.edu.au/cpg/about-rif-cs
​
Cheers
Richard

**Comment by leskneebone** [comment]
A [draft proposal](https://docs.google.com/document/d/1slJKiPvJFqGS8L8IDjy7CCjdctTj2cfGSaJpm-DwtsU/edit?usp=sharing) is ready to review. I'm inviting internal review (probably this means @nicholascar) before sending this to ARDC.

Three changes are proposed:

- New concept “Language group”
- New concept “Austlang language codes”
- Updated description for “Group”

I considered a fourth change where the AIATSIS thesaurus of places would be added to Spatial type - but the status of that vocabulary seems uncertain. It would be good to get a better understanding of the [AIATSIS thesauri ](https://aiatsis.gov.au/thesaurus)and how they fit in, if at all, to the IDN.

**Comment by leskneebone** [comment]
Hi @nicholascar , can you review the [draft proposal](https://docs.google.com/document/d/1slJKiPvJFqGS8L8IDjy7CCjdctTj2cfGSaJpm-DwtsU/edit?usp=sharing) please.

**Comment by leskneebone** [comment]
mailed proposal doc today.

**Comment by lalewis1** [comment]
changes submitted to ARDC and waiting for feedback.

**Comment by leskneebone** [comment]
ARDC ref: HELP-1442 RIF-CS change proposal

**Comment by nicholascar** [comment]
Reviewing tomorrow

**Comment by nicholascar** [comment]
I have made some minor additions to the proposal Google Doc, including providing an austLang language code example.

Can the following still be added please:

1. An example of an Indigenous dataset Record in current RIF-CS XML
2. The same Record in IDN-enhanced RIF-CS XML, using the new elements
3. Some discussion of how the new elements lead to a better understanding of the Record's indigeneity
4. Analysis of how these additions (plus perhaps more) support the same sort of indigeneity assessment as schema.org + IDN additions metadata does - CARE scores in particular

For point 4, we will need improved examples of RDF metadata in the [IDN Catalogue Profile](https://data.idnau.org/pid/cp).
