### ISSUE TITLE
Create a data terminology glossary vocab

### ISSUE THREAD

**Issue by Metaduck** [idn-au/vocab-data#26]
Create a vocabulary of data-related terminology - a glossary - for use by end users of IDN systems & methods and partners.

The glossary may need to be presented in various physical/digital forms, may need to be in multiple languages and certainly must have common use definitions.

This Glossary will support training and use of IDN resources.

**Comment by Metaduck** [comment]
Need to catch up with Levi at the Uni Melb.

**Comment by leskneebone** [comment]
Meeting scheduled Levi (and Trent) for 10am Monday 23 September. I guess if either @nicholascar or @Metaduck want to join, let me know. In any case I'll get what I can from Levi regarding what needs to go in said glossary.

**Comment by leskneebone** [comment]
Met with Levi and Kristen at their office on Parkville campus (Unimelb). **They will get back to us with a specific case study to work with**, including a specific Indigenous language to translate vocabs as a starting point. Either Milingimbi keeping place or Yirrkala language production centre will be the likely context for starting this work.

Levi noted that there will be example where glossary terms may exist in an Australian language but not have an English equivalent. This scenario might stretch VocPub rules around how multilingual labels are treated. Currently VocPub specification 2.1.4 note reads:
"...labels in multiple languages should be indicated with skos:altLabel predicates, not all with skos:prefLabel, i.e. there should only ever be one skos:prefLabel value. If multiple definitions are given, the one in the language of the label is considered primary. The VocExcel template seems to implement this, with direct translations stored as altLabels. Given the restriction of only one PrefLabel (in any language) per concept, how would synonyms between non default language terms be controlled? And what if a translation (non-default) concept has no default language equivalent, does that not break the VocPub specification?

We discussed the possibility of Indigenous language terms being treated (in this case) as 'load words' - so a label would be stored for both an Indigenous language and also for English. This approach was taken in the biosecurity thesaurus for an Indonesian concept that had no English translation (see [Nangluk merana](https://umelb-pp.poolparty.biz/biosecurityThesaurus/dd4d68bf-845b-44c6-9a40-e2a730ed4558))

Notes about case study contexts:

Milingimbi keeping place
- keeping place is adapted from an Indonesian model
- Governance is adapted and local
- We need to look at their existing glossaries
- Use their database as example
- Collected works are from multiple institutions
- Jacinta is a librarian working at Milingimbi

Yirrkala language production centre
- Living archive frequently updated and about 1/4 petabytes of data

**Comment by leskneebone** [comment]
Draft vocab is up on demo Prez server:
https://demo.dev.kurrawong.ai/catalogs/exm:demo-vocabs/collections/ns39:glossary
